name = "techfix-backend"
main = "worker.js"
compatibility_date = "2024-01-01"

# Automatically handle variables/secrets like JWT_SECRET through Cloudflare Dashboard or .dev.vars locally
[vars]
# Add non-sensitive variables here

[[d1_databases]]
binding = "DB" # This corresponds to env.DB in worker.js
database_name = "techfix-db"
database_id = "ec5afab2-05ef-4b73-837d-963fe460d3db"
# preview_database_id = "YOUR_PREVIEW_DATABASE_ID_HERE"
